import multiprocessing as mp
import warnings
from collections.abc import Sequence
from typing import Literal

import keras
import numpy as np
import sympy as sp

from bayesflow.approximators import Approximator
from bayesflow.networks import InferenceNetwork, SummaryNetwork
from bayesflow.types import Shape
from bayesflow.utils import find_batch_size, logging
from bayesflow.utils.serialization import deserialize, serializable, serialize

from ...adapters import Adapter
from ...datasets import OfflineDataset, OnlineDataset
from ...networks.helpers.standardization.standardize import Standardize
from ..graphical_simulator import GraphicalSimulator, SimulationOutput
from ..graphs import InvertedGraph
from .inference_conditions import inference_conditions_by_network
from .inference_variables import inference_variable_shapes_by_network, inference_variables_by_network, resolve_shapes
from .non_exchangeable_wrapper import NonExchangeableWrapper


@serializable("bayesflow.experimental")  # type: ignore[missing-argument]
class GraphicalApproximator(Approximator):
    """
    Amortized inference for probabilistic models defined by directed acyclic graphs.

    This approximator implements amortized Bayesian inference for simulation-based
    models whose probabilistic structure can be expressed as a directed acyclic
    graph (DAG). The dependency structure is encoded in an
    :class:`bayesflow.experimental.graphs.InvertedGraph`, which specifies the order
    in which variables are summarized, conditioned on, and inferred.
    """

    def __init__(
        self,
        graph: InvertedGraph,
        *,
        adapter: Adapter | Literal["auto"] = "auto",
        inference_networks: Sequence[InferenceNetwork],
        summary_networks: Sequence[SummaryNetwork] | None = None,
        standardize: str | list[str] | None = "all",
        **kwargs,
    ):
        """
        Parameters
        ----------
        graph : bayesflow.experimental.graphs.InvertedGraph
            InvertedGraph capturing the dependency structure. Usually obtained by calling
            the :py:meth:`invert` method of a :py:class:`SimulationGraph`.
        adapter : bayesflow.adapters.Adapter
            Adapter for data processing. You can use :py:meth:`build_adapter`
            to create it.
        inference_networks : list[InferenceNetwork]
            The inference networks used for posterior estimation.
            Each network is responsible for a subset of variables, as
            determined by the network composition defined by the supplied `graph`.
            Call the :py:meth:`network_composition` method of the `InvertedGraph` for an
            overview of how variables are assigned to inference networks.
        summary_networks : list[SummaryNetwork], optional
            The summary networks used for data summarization (default is None).
        standardize : str | Sequence[str] | None
            The variables to standardize before passing to the networks. Can be either
            "all" or any subset of the variables generated by the SimulationGraph contained
            in the `simulation_graph` field of the supplied InvertedGraph (default is "all").
        **kwargs : dict, optional
            Additional arguments passed to the :py:class:`bayesflow.approximators.Approximator` class.
        """

        super().__init__(**kwargs)
        self.graph = graph
        self.adapter = adapter
        self.inference_networks = inference_networks
        self.summary_networks = summary_networks

        required = self.graph.summary_network_input_shapes()
        data_keys = [k for k in required if k.mode != "non_exchangeable"]
        n_data = len(data_keys)
        n_nonex = len(required) - n_data
        n_provided = len(summary_networks or [])

        if n_provided != len(required):
            if n_nonex:
                raise ValueError(
                    f"Expected {len(required)} summary networks ({n_data} data + {n_nonex} non-exchangeable), "
                    f"got {n_provided}."
                )
            else:
                raise ValueError(f"Expected {n_data} summary networks, got {n_provided}.")

        data_summary_networks = (summary_networks or [])[:n_data]
        nonex_summary_networks = (summary_networks or [])[n_data:]
        self.summary_registry = dict(zip(data_keys, data_summary_networks))

        # precompute frequently used quantities
        self.output_shapes = self.graph.simulation_graph.output_shapes()
        self.network_composition = self.graph.network_composition()
        self.network_conditions = self.graph.network_conditions()
        self.variable_names = self.graph.simulation_graph.variable_names()

        if isinstance(standardize, str) and standardize != "all":
            self.standardize = [standardize]
        else:
            self.standardize = standardize or []

        if standardize == "all":
            self._standardize_layers = None
        else:
            self._standardize_layers = {var: Standardize(trainable=False) for var in self.standardize}

        if adapter == "auto":
            self.adapter = GraphicalApproximator.build_adapter()

        # wrap non-amortizable inference networks in NonExchangeableWrapper
        required_nonex = self.graph.non_amortizable_summary_input_shapes()
        for i, network_idx in enumerate(required_nonex):
            self.inference_networks[network_idx] = NonExchangeableWrapper(
                self.inference_networks[network_idx], nonex_summary_networks[i]
            )

    @property
    def standardize_layers(self):
        return self._standardize_layers

    @classmethod
    def build_adapter(
        cls,
    ) -> Adapter:
        """Create an :py:class:`~bayesflow.adapters.Adapter` suited for the approximator."""

        adapter = Adapter()
        adapter.to_array()
        adapter.convert_dtype("float64", "float32")

        return adapter

    def build_dataset(
        self,
        *,
        batch_size: int,
        num_batches: int,
        adapter: Adapter | None = None,
        simulator: GraphicalSimulator,
        workers: Literal["auto"] | int = "auto",
        use_multiprocessing: bool = False,
        max_queue_size: int = 32,
        **kwargs,
    ) -> OnlineDataset:
        if workers == "auto":
            workers = mp.cpu_count()
            logging.info(f"Using {workers} data loading workers.")

        workers = workers or 1

        return OnlineDataset(
            simulator=simulator,
            batch_size=batch_size,
            num_batches=num_batches,
            adapter=adapter,
            workers=workers,
            use_multiprocessing=use_multiprocessing,
            max_queue_size=max_queue_size,
            augmentations=lambda x: dict(x),
            **kwargs,
        )

    @classmethod
    def from_config(cls, config):
        return cls(**deserialize(config))

    def get_config(self):
        base_config = super().get_config()
        # Unwrap NonExchangeableWrapper so __init__ doesn't double-wrap on reload.
        inference_networks = [
            n.inference_network if isinstance(n, NonExchangeableWrapper) else n for n in self.inference_networks
        ]
        config = {
            "graph": self.graph,
            "adapter": self.adapter,
            "inference_networks": inference_networks,
            "summary_networks": self.summary_networks,
            "standardize": self.standardize,
        }

        return base_config | serialize(config)

    def build(self, data_shapes: dict | None = None, meta_dict: dict | None = None) -> None:
        if not data_shapes:
            data_shapes = self.output_shapes

        resolved_meta = self._meta_dict_from_data_shapes(data_shapes) | (meta_dict or {})

        def _build_network(network, input_shape):
            if not network.built:
                concrete_shape = tuple(int(d.subs(resolved_meta)) if isinstance(d, sp.Expr) else d for d in input_shape)
                network.build(concrete_shape)

        # build non-exchangeable summary networks inside their wrappers
        for network_idx, input_shape in self.graph.non_amortizable_summary_input_shapes().items():
            wrapper = self.inference_networks[network_idx]
            if isinstance(wrapper, NonExchangeableWrapper):
                _build_network(wrapper.summary_network, input_shape)

        # build standardization layers
        output_shapes = resolve_shapes(data_shapes, meta_dict)

        if self.standardize == "all":
            self.standardize = list(output_shapes.keys())
            self._standardize_layers = {var: Standardize(trainable=False) for var in self.standardize}

        for var in self.standardize:
            self._standardize_layers[var].build(output_shapes[var])

        self.built = True

    def build_from_data(self, adapted_data):
        Approximator.build_from_data(self, adapted_data)
        # run a forward pass so inference networks are lazily built before
        # Keras's _symbolic_build checks for unbuilt layers
        self.compute_metrics(**adapted_data)

    def call(self, data, **kwargs):
        return self.compute_metrics(**data, **kwargs)

    def compute_metrics(self, stage: str = "training", **kwargs):
        """
        Computes loss and tracks metrics for the inference and summary networks.

        This method orchestrates the end-to-end computation of metrics and loss for a model
        with both inference and optional summary network. It handles standardization of input
        variables, combines summary outputs with inference conditions when necessary, and
        aggregates loss and all tracked metrics into a unified dictionary. The returned dictionary
        includes both the total loss and all individual metrics, with keys indicating their source.

        Parameters
        ----------
        stage : str, optional
            Current training stage (e.g., "training", "validation", "inference"). Controls
            the behavior of standardization and some metric computations (default is "training").

        Returns
        -------
        metrics : dict[str, Tensor]
            Dictionary containing the total loss under the key "loss", as well as all tracked
            metrics for the inference networks. Each metric key is prefixed with
            ``inference_metrics_<i>/`` where ``i`` is the network index.
        """
        inference_variables = inference_variables_by_network(self, kwargs)
        inference_conditions = inference_conditions_by_network(
            self, kwargs, self.summary_registry, training=stage == "training"
        )

        total_loss = 0
        combined_metrics = {}

        for i, inference_network in enumerate(self.inference_networks):
            metrics = inference_network.compute_metrics(
                inference_variables[i], conditions=inference_conditions[i], stage=stage
            )
            if "loss" in metrics:
                total_loss += metrics["loss"]
            for k, v in metrics.items():
                combined_metrics[f"inference_metrics_{i}/{k}"] = v

        combined_metrics["loss"] = total_loss

        return combined_metrics

    def fit(self, *args, **kwargs):
        """
        Trains the approximator on the provided dataset or on-demand data generated from the given simulator.
        If `dataset` is not provided, a dataset is built from the `simulator`.
        If the model has not been built, it will be built using a batch from the dataset.

        Parameters
        ----------
        dataset : keras.utils.PyDataset, optional
            A dataset containing simulations for training. If provided, `simulator` must be None.
        simulator : Simulator, optional
            A simulator used to generate a dataset. If provided, `dataset` must be None.
        **kwargs
            Additional keyword arguments passed to `keras.Model.fit()`, including (see also `build_dataset`):

            batch_size : int or None, default='auto'
                Number of samples per gradient update. Do not specify if `dataset` is provided as a
                `keras.utils.PyDataset`, `tf.data.Dataset`, `torch.utils.data.DataLoader`, or a generator function.
            epochs : int, default=1
                Number of epochs to train the model.
            verbose : {"auto", 0, 1, 2}, default="auto"
                Verbosity mode. 0 = silent, 1 = progress bar, 2 = one line per epoch.
            callbacks : list of keras.callbacks.Callback, optional
                List of callbacks to apply during training.
            validation_split : float, optional
                Fraction of training data to use for validation (only supported if `dataset` consists of NumPy arrays
                or tensors).
            validation_data : tuple or dataset, optional
                Data for validation, overriding `validation_split`.
            shuffle : bool, default=True
                Whether to shuffle the training data before each epoch (ignored for dataset generators).
            initial_epoch : int, default=0
                Epoch at which to start training (useful for resuming training).
            steps_per_epoch : int or None, optional
                Number of steps (batches) before declaring an epoch finished.
            validation_steps : int or None, optional
                Number of validation steps per validation epoch.
            validation_batch_size : int or None, optional
                Number of samples per validation batch (defaults to `batch_size`).
            validation_freq : int, default=1
                Specifies how many training epochs to run before performing validation.

        Returns
        -------
        keras.callbacks.History
            A history object containing the training loss and metrics values.

        Raises
        ------
        ValueError
            If both `dataset` and `simulator` are provided or neither is provided.
        """
        if "dataset" in kwargs:
            raw_data = kwargs.pop("dataset")
            batch_size = kwargs.get("batch_size", "auto")
            if batch_size == "auto":
                first_sample = {k: v[:1] for k, v in raw_data.items()}
                batch_size = find_batch_size(sample=first_sample)
                logging.info(f"Using a batch size of {batch_size}.")
            dataset = OfflineDataset(
                raw_data,
                batch_size=batch_size,
                num_samples=kwargs.get("num_samples"),  # type: ignore[invalid-argument-type]
                adapter=self.adapter,
                augmentations=self.subset_data,
            )

            def generator():
                for i in range(dataset.num_batches or 0):
                    yield dataset[i]

        if "simulator" in kwargs:
            dataset = self.build_dataset(
                simulator=kwargs.pop("simulator"),
                adapter=kwargs.get("adapter"),
                batch_size=kwargs["batch_size"],
                num_batches=kwargs["num_batches"],
            )

            def generator():
                i = 0
                while True:
                    yield dataset[i]
                    i += 1

        if keras.backend.backend() == "tensorflow":
            import tensorflow as tf

            first_batch = dataset[0]
            data_shapes = self._data_shapes(first_batch)
            self.compute_metrics(**first_batch)
            if not self.built:
                self.build(data_shapes)

            signature = {
                k: tf.TensorSpec(shape=[None] * (len(v) - 1) + [v[-1]], dtype=tf.float32)
                for k, v in data_shapes.items()
            }
            kwargs.setdefault("steps_per_epoch", dataset.num_batches)
            kwargs["dataset"] = tf.data.Dataset.from_generator(generator, output_signature=signature).repeat()
        else:  # pragma: no cover
            kwargs["dataset"] = dataset

        return super().fit(*args, **kwargs, adapter=self.adapter)

    def sample(self, *, num_samples: int, conditions: dict[str, np.ndarray]) -> dict[str, np.ndarray]:
        meta_dict = self._meta_dict_from_data(conditions)

        variable_names = self.graph.simulation_graph.variable_names()
        data_node = self.graph.simulation_graph.data_node()
        batch_size = self._batch_size_from_data(conditions)
        batch_n = batch_size * num_samples

        variable_shapes = inference_variable_shapes_by_network(self, meta_dict=meta_dict)
        data_variables = variable_names[data_node]
        inference_conditions = {}

        # add num_samples as repeats across the batch dimension
        for name in data_variables:
            inference_conditions[name] = keras.ops.repeat(conditions[name], num_samples, axis=0)

        # build new inference conditions incrementally: after each network samples,
        # add its output to inference_conditions so later networks can condition on it
        for i, inference_network in enumerate(self.inference_networks):
            all_conds = inference_conditions_by_network(
                self, inference_conditions, self.summary_registry, only_network=i
            )
            cond = all_conds[i]
            variable_shape = list(variable_shapes[i])
            variable_shape[0] = batch_n

            samples = inference_network.sample(tuple(variable_shape[:-1]), conditions=cond)

            j = 0
            for node in self.network_composition[i]:
                for variable in variable_names[node]:
                    var_dim = int(self.output_shapes[variable][-1])
                    sample = samples[..., j : (j + var_dim)]
                    if variable in self.standardize:
                        sample = self._standardize_layers[variable](sample, forward=False)
                    inference_conditions[variable] = sample
                    j += var_dim

        # reshape samples
        result = {}
        for k, v in inference_conditions.items():
            if k not in data_variables:
                result[k] = keras.ops.convert_to_numpy(
                    keras.ops.reshape(v, (batch_size, num_samples, *keras.ops.shape(v)[1:]))
                )

        result = self.adapter.inverse(result)
        return result

    def log_prob(self, data):
        variable_names = self.graph.simulation_graph.variable_names()
        adapted, ldj_adapter = self.adapter(data, log_det_jac=True)
        batch_size = self._batch_size_from_data(data)
        log_prob = keras.ops.zeros(batch_size)

        variables = inference_variables_by_network(self, adapted)
        conditions = inference_conditions_by_network(self, adapted, self.summary_registry)

        # log_probs
        for i, inference_network in enumerate(self.inference_networks):
            log_prob_i = inference_network.log_prob(variables[i], conditions[i])
            log_prob += keras.ops.sum(keras.ops.reshape(log_prob_i, (batch_size, -1)), axis=-1)

        # log_det_jac for standardization layers
        for node, variable_names in variable_names.items():
            for variable_name in variable_names:
                if variable_name in (self._standardize_layers or {}):
                    result, ldj = self._standardize_layers[variable_name](adapted[variable_name], log_det_jac=True)
                    log_prob += keras.ops.sum(keras.ops.reshape(ldj, (batch_size, -1)), axis=-1)

        # log_det_jac for adapter
        for key in ldj_adapter:
            ldj = keras.ops.cast(ldj_adapter[key], "float32")
            log_prob += keras.ops.sum(keras.ops.reshape(ldj, (batch_size, -1)), axis=-1)

        return log_prob

    def subset_data(self, data, meta_fn=None):
        output_shapes = self.graph.simulation_graph.output_shapes()

        if not meta_fn:
            meta_fn = self.graph.simulation_graph.meta_fn
            if meta_fn:
                output_shapes = self.graph.simulation_graph.output_shapes(meta_fn())

        output = {}

        for k, v in data.items():
            if k not in output_shapes:
                raise KeyError(f"Unexpected data entry: {k}")

            begin = (0,) * len(keras.ops.shape(v))

            output_shape = list(output_shapes[k])
            actual_shape = keras.ops.shape(v)
            for j in range(len(output_shape)):
                if isinstance(output_shape[j], sp.Expr):
                    output_shape[j] = actual_shape[j]
                else:
                    output_shape[j] = min(output_shape[j], int(actual_shape[j]))
            output_shape = tuple(output_shape)

            # current keras version throws a deprecation warning when using keras.ops.slice even if
            # called approriately
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", message="Using a non-tuple sequence")
                output[k] = keras.ops.convert_to_numpy(keras.ops.slice(v, begin, output_shape))

        return output

    def _meta_dict_from_data(self, data: dict[str, np.ndarray]) -> dict[str, Shape]:
        """
        Infers meta information (sympy symbol → concrete value) from data shapes by comparing
        the symbolic template shapes against the concrete shapes of the observed data.
        """
        data_shapes = self._data_shapes(data)
        return self._meta_dict_from_data_shapes(data_shapes)

    def _meta_dict_from_data_shapes(self, data_shapes) -> dict[str, Shape]:
        meta_dict = {}
        output_shapes = self.graph.simulation_graph.output_shapes()

        for k, v in data_shapes.items():
            for dim_t, dim_c in zip(output_shapes.get(k, ()), v):
                if isinstance(dim_t, sp.Expr):
                    for sym in dim_t.free_symbols:
                        if sym not in meta_dict:
                            meta_dict[sym] = dim_c

        return meta_dict

    def _batch_size_from_data(self, data):
        """
        Fetches the current batch size from an input dictionary.
        """
        for key, value in data.items():
            if hasattr(value, "shape"):
                return keras.ops.shape(value)[0]

    def _data_shapes(self, adapted_data: SimulationOutput | dict) -> dict[str, tuple[int]]:
        def _shape_tuple(x) -> tuple[int, ...]:
            shape = keras.ops.shape(x)
            return tuple(int(i) for i in keras.ops.convert_to_numpy(shape))

        return keras.tree.map_structure(_shape_tuple, dict(adapted_data))
