channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - keras
  - numpy
  - matplotlib
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-xdist
  - python >= 3.12, < 3.14
  - ruff
  - seaborn
  - pandas
  - scikit-learn
  - scipy
  - tqdm
  - tox
