from collections.abc import Sequence

import keras

from bayesflow.types import Tensor
from bayesflow.utils.serialization import serializable, serialize

from .equivariant_layer import EquivariantLayer
from .invariant_layer import InvariantLayer

from ...summary import SummaryNetwork


@serializable("bayesflow.networks")
class DeepSet(SummaryNetwork):
    """(SN) Implements a deep set encoder introduced in [1] for learning permutation-invariant representations of
    set-based data, as generated by exchangeable models.

    [1] Zaheer, M., Kottur, S., Ravanbakhsh, S., Poczos, B., Salakhutdinov, R. R., & Smola, A. J. (2017).
    Deep sets. Advances in neural information processing systems, 30.
    """

    def __init__(
        self,
        summary_dim: int = 16,
        embed_dim: int = 64,
        depth: int = 2,
        mlp_widths: Sequence[int] = (64,),
        inner_pooling: str = "mean",
        output_pooling: str = "mean",
        activation: str = "silu",
        kernel_initializer: str = "he_normal",
        dropout: float | None = 0.05,
        **kwargs,
    ):
        """
        Initializes a deep set model for learning permutation-invariant representations.

        A stack of equivariant layers (each injecting a pooled invariant summary back into
        every set element via a Pre-LN residual block) is followed by a single invariant
        layer and a linear output projection.

        Parameters
        ----------
        summary_dim : int, optional
            Dimensionality of the final learned summary statistics. Default is 16.
        embed_dim : int, optional
            Working dimensionality shared across all equivariant and invariant layers.
            Default is 64.
        depth : int, optional
            Number of stacked equivariant modules. Default is 2.
        mlp_widths : Sequence[int], optional
            Hidden layer widths for the MLPs inside each equivariant and invariant layer.
            The output of each MLP is always ``embed_dim``. Default is ``(64,)``.
        inner_pooling : str, optional
            Pooling used inside the equivariant modules. Default is ``"mean"``.
        output_pooling : str, optional
            Pooling used in the final invariant module. Default is ``"mean"``.
        activation : str, optional
            Activation function used throughout. Default is ``"silu"``.
        kernel_initializer : str, optional
            Weight initializer for Dense projections. Default is ``"he_normal"``.
        dropout : float or None, optional
            Dropout rate. Default is 0.05.
        **kwargs
            Additional keyword arguments passed to the base class.
        """
        super().__init__(**kwargs)

        self.summary_dim = summary_dim
        self.embed_dim = embed_dim
        self.depth = depth
        self.mlp_widths = tuple(mlp_widths)
        self.inner_pooling = inner_pooling
        self.output_pooling = output_pooling
        self.activation = activation
        self.kernel_initializer = kernel_initializer
        self.dropout_rate = dropout

        self.equivariant_modules = [
            EquivariantLayer(
                embed_dim=embed_dim,
                mlp_widths=mlp_widths,
                pooling=inner_pooling,
                activation=activation,
                kernel_initializer=kernel_initializer,
                dropout=dropout,
            )
            for _ in range(depth)
        ]

        self.invariant_module = InvariantLayer(
            embed_dim=embed_dim,
            mlp_widths=mlp_widths,
            pooling=output_pooling,
            activation=activation,
            kernel_initializer=kernel_initializer,
            dropout=dropout,
        )

        self.output_projector = keras.layers.Dense(units=summary_dim, kernel_initializer=kernel_initializer)

    def call(self, x: Tensor, training: bool = False, **kwargs) -> Tensor:
        for em in self.equivariant_modules:
            x = em(x, training=training)
        x = self.invariant_module(x, training=training)
        return self.output_projector(x)

    def get_config(self):
        base_config = super().get_config()
        return base_config | serialize(
            {
                "summary_dim": self.summary_dim,
                "embed_dim": self.embed_dim,
                "depth": self.depth,
                "mlp_widths": self.mlp_widths,
                "inner_pooling": self.inner_pooling,
                "output_pooling": self.output_pooling,
                "activation": self.activation,
                "kernel_initializer": self.kernel_initializer,
                "dropout": self.dropout_rate,
            }
        )
