name: Check Code Style

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  check-code-style:
    name: Check Code Style

    runs-on: ubuntu-latest

    permissions: {}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Setup Environment
        run: uv venv

      - name: Install Dependencies
        run: uv pip install ruff

      - name: Run Linter
        run: uv run ruff check --config pyproject.toml --verbose

      - name: Run Formatter
        run: uv run ruff format --config pyproject.toml --check --verbose
